### PR TITLE
Add brooklyn-terraform

### PR DESCRIPTION
**Pull request by sjcorbett**

### CODE REVIEW

**Comment by sjcorbett** [comment]
@tbouron the bot failed because
```
Caused by: io.cloudsoft.catalog.util.CatalogValidationException: The overview file located at https://github.com/cloudsoft/brooklyn-terraform/blob/master/README.md does not exist
	at io.cloudsoft.catalog.util.CatalogValidator.validate(CatalogValidator.java:133)
	at 
```
But that file definitely exists. Does it want the raw URL?

**Comment by tbouron** [comment]
@sjcorbett Yes, the validator expects the raw URL.

**Comment by sjcorbett** [comment]
@tbouron it also thinks https://raw.githubusercontent.com/cloudsoft/brooklyn-terraform/master/README.md doesn't exist. Any suggestions?

**Comment by tbouron** [comment]
@sjcorbett Ah, that's the `overview`, I didn't realise that before, my bad! It expects a relative path so in your case, it should simply be  `README.md`

**Comment by tbouron** [comment]
@sjcorbett Are you happy for me to merge this one?

**Comment by sjcorbett** [comment]
Yes please

**Pull request merged**
