### PR TITLE
Fix for false negative & Config tweaks

### PR DESCRIPTION
**Pull request by m4rkmckenna**
- Validation will no longer fail on a PR that does not touch directory.yaml
- Changed enviroment variables to system properties
  PR_NUMBER -> prNumber
  AUTH_TOKEN -> authToken
  DIRECTORY_REOP_URI -> directoryRepoURI

Example usage
`mvn clean install -DprNumber=14 -DauthToken=abc123xyz`

### CODE REVIEW

**Comment by m4rkmckenna** [comment]
retest this please

**Comment by tbouron** [comment]
LGTM - Just need to make sure the Jenkins config is setup properly

**Comment by m4rkmckenna** [comment]
retest this please

**Comment by tbouron** [comment]
All tests are green, merging

**Pull request merged**
