### PR TITLE
Added brooklyn-elasticsearch

### PR DESCRIPTION
**Pull request by Graeme-Miller**

### CODE REVIEW

**Comment by tbouron** [comment]
Sorry @Graeme-Miller I just saw your PR.

You miss the `README.md` in your repo [which is a required file](https://github.com/brooklyncentral/brooklyn-community-catalog). Could you add it please?

**Comment by Graeme-Miller** [comment]
Sure, I have added that now

**Comment by tbouron** [comment]
Could you also rebase on the latest master please? Thanks @Graeme-Miller !

**Comment by Graeme-Miller** [comment]
@tbouron done

**Comment by tbouron** [comment]
Thanks, merged!

**Pull request merged**
