### PR TITLE
Add Brooklyn Hyperledger project

### PR DESCRIPTION
**Pull request by sjcorbett**

### CODE REVIEW

**Comment by sjcorbett** [comment]
@tbouron Any comments?

**Comment by tbouron** [comment]
Humm weird, the PR should have been tested automatically.

Let me try to restart it

**Comment by tbouron** [comment]
retest this please

**Comment by tbouron** [comment]
retest this please

**Comment by tbouron** [comment]
retest this please

**Comment by tbouron** [comment]
@sjcorbett Jenkins needed an update to run properly...

Tests passed, merging!

**Comment by sjcorbett** [comment]
@tbouron Thanks.

**Pull request merged**
